# Generated by Django 3.0.5 on 2020-05-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200502_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='sample'),
            preserve_default=False,
        ),
    ]
