# Generated by Django 3.0.5 on 2020-05-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-CreateTime',)},
        ),
    ]
