# Generated by Django 3.0.1 on 2020-06-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200518_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
