# Generated by Django 3.0.1 on 2020-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_defaultimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_hai',
            field=models.TextField(blank=True),
        ),
    ]
