# Generated by Django 3.0.1 on 2020-06-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_images_image_hai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_hai',
        ),
        migrations.AddField(
            model_name='post',
            name='image_hai',
            field=models.TextField(blank=True),
        ),
    ]
