# Generated by Django 3.0.1 on 2020-06-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200615_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultImage',
        ),
    ]
