# Generated by Django 3.0.5 on 2020-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sap',
            field=models.IntegerField(default=500068749, unique=True),
            preserve_default=False,
        ),
    ]
