# Generated by Django 3.0.6 on 2020-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200518_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Krishna Mathuria', max_length=200),
            preserve_default=False,
        ),
    ]
