# Generated by Django 3.0.1 on 2020-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sap',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(unique=True),
        ),
    ]
