# Generated by Django 3.0.6 on 2020-06-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200526_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='Krishna Mathuria', max_length=200),
            preserve_default=False,
        ),
    ]
